### PR TITLE
Disabled coveralls

### PR DESCRIPTION
**Pull request by myui**
Disabled coverall to avoid 

```
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

follow up to #102

### CODE REVIEW

**Comment by myui** [comment]
@chezou could you take a look?

**Comment by chezou** [comment]
Change itself looks good to me.

However I'm not an active maintainer of this project as well, and I don't know the historical things for coverall so that I'd like for @yyuu to ask to have another look at this.

**Review by yyuu — APPROVED** [review]
To be quite honest, I don't think I am the right one to give approval, however, the change looks legit for short term remediation to the issue. We could be requested to calculate test coverage to ensure the library is providing sane behavior, however, we actually wasn't requested to use specific service to do it. I think it's okay to go with disabling Coveralls for time being.

**Review by chezou — APPROVED** [review]

**Comment by chezou** [comment]
@yyuu Thanks for having time for another review. Apologies I totally forgot to approve the PR with my previous comment.

**Comment by myui** [comment]
Thanks, disable coveralls for the time being.

**Pull request merged**
