### PR TITLE
Fixed Coveralls submission failure

### PR DESCRIPTION
**Pull request by myui**
Fixed recent coverall submission failure.

See 
https://github.com/treasure-data/td-client-python/pull/101/checks?check_run_id=2251175902

### CODE REVIEW

**Review by yyuu — COMMENTED** [review]
@myui 
First of all, I'm no longer an active maintainer of the project. It'd be better asking @chezou for review :pray:

Second, CI is failing w/ same error even after the changes means your fix isn't complete 😕  It seems, the project is currently [configured to use coveralls 1.1](https://github.com/treasure-data/td-client-python/blob/1.2.1/test-requirements.txt#L1), and apparently `--service` option was added starting from 1.3.0 by https://github.com/TheKevJames/coveralls-python/pull/167 . I'd suggest to tweak the project's dependency configuration first.

**Comment by myui** [comment]
@yyuu thanks.  Updated coverall. I guess no active maintainer for this project... 

```
Collecting coveralls<2.0.0,>=1.1
  Downloading coveralls-1.11.1-py2.py3-none-any.whl (12 kB)

root@a8ae87f0a83c:~/td-client-python# coveralls  --help | grep service
sends it to the coveralls.io service API.
All Python files in your coverage analysis are posted to this service along
    --service=<name>  Provide an alternative service name to submit.
```

confirmed test works. @chezou could you take a look?

**Comment by chezou** [comment]
Looks like CI is still failing 😢

**Comment by myui** [comment]
?? ttps://github.com/lemurheavy/coveralls-public/issues/1435

maybe we need to use the latest version of coverall.
https://github.com/TheKevJames/coveralls-python/blob/master/CHANGELOG.md

**Comment by myui** [comment]
not sure why debug mode resolved issue ... 😟

**Comment by myui** [comment]
It's seems it's due to coverall APIs, not configuration. 

Better to disable coverall for now.

**Pull request closed without merging**
