### PR TITLE
[WIP] Move tests outside of source directory

### PR DESCRIPTION
**Pull request by scottso**
This causes issues with running tox.

Added testing for python 3.6

### CODE REVIEW

**Comment by scottso** [comment]
This obviously isn't ready yet.  Just want to get initial stuff put here until I have time to work on it.

**Comment by yyuu** [comment]
Actually I don't have any trouble running `tox` with current configuration.... What's the issue?

Anyway I'll give +1 to move out tests from library directory :+1:

**Comment by chezou** [comment]
Close this PR since it seems unmaintained for a long time. Feel free to reopen if needed.

**Comment by scottso** [comment]
It was open this long because I left the company.  At the time it worked.  Not sure why it never got merged.

**Pull request closed without merging**
